### PR TITLE
Ghc 8.10

### PR DESCRIPTION
**Pull request by mightybyte**
This is an update to phadej's pull request bumping the bounds for tasty and criterion to trigger CI.

### CODE REVIEW

**Comment by mightybyte** [comment]
Marked as ready for review to trigger CI.

**Comment by mightybyte** [comment]
It looks like these changes have passed CI.  https://travis-ci.org/github/haskell-hvr/cryptohash-sha512

**Comment by dbaynard** [comment]
Would it be possible for one of the maintainers to review this PR?

**Comment by nbouscal** [comment]
@hvr

**Comment by nbouscal** [comment]
@hvr Can we please get this merged? It's the last thing blocking us on 8.10.

**Comment by nbouscal** [comment]
@hvr I guess tagging you isn't a good way to bring this to your attention, but here's one last try

**Comment by Anton-Latukha** [comment]
Just noted that the whole `cryptohash*` family is deprecated: https://github.com/vincenthz/hs-cryptohash#readme in favor of `cryptonite` family.

**Comment by nbouscal** [comment]
> Just noted that the whole `cryptohash*` family is deprecated: https://github.com/vincenthz/hs-cryptohash#readme in favor of `cryptonite` family, SHA512 is there also. — @Anton-Latukha 

From the package description in this repository:

> NOTE: This package has been forked off @cryptohash-0.11.7@ because the @cryptohash@ package has been
>    deprecated and so this package continues to satisfy the need for a lightweight package
>    providing the SHA512 hash algorithm without any dependencies on packages other than
>    @base@ and @bytestring@.

**Comment by Anton-Latukha** [comment]
I made a fork of this PR and brought it up to date, provided support for both epochs of `base16-bytestring`, new one was released recently. Also removed some dependency bounds to make stale package not constrain the dependencies and so patch for hardcode override would work for some time without changes:

The fork is in https://github.com/Anton-Latukha/cryptohash-sha512/tree/ghc-8.10

To override - add the `cabal.package` file with:
```
packages: .

source-repository-package
    type: git
    location: https://github.com/Anton-Latukha/cryptohash-sha512
    tag: 48f827eb09a73ad5ee43dd397a06ebdbf51ab856
```

We currently have a small stack of software built on it: `hnix-store-core`, `hnix-store-remote`, `hnix` and what depends on them. I do not need to tell you that we now need to migrate from the library asap, or normalize this situation somehow.

**Comment by sjakobi** [comment]
I've asked the Hackage Trustees to make a revision: https://github.com/haskell-infra/hackage-trustees/issues/289

**Comment by endgame** [comment]
I have used hackage trustee powers to apply the updated bounds in this PR as a new metadata revision. I have not copy/pasted the whole cabal file because the description changed: the description is shorter and drops the discussion of the wider `cryptohash-*` ecosystem. What's the status of the other `cryptohash-*` packages, and do they need PRs and metadata updates?

**Comment by Anton-Latukha** [comment]
> What's the status of the other `cryptohash-*` packages, and do they need PRs and metadata updates?

We use the whole `cryptohash-*` family and this is the first package to turn stale.
Probably soon would need to update others. SHA-512 just is a less used lib, so updates to it got later, so got in the unresponcive window. If the window continues - of course the next base the other packages would follow.

**Comment by Anton-Latukha** [comment]
> revision

Than you Simon.

**Comment by ysangkok** [comment]
@Anton-Latukha 

> Just noted that the whole cryptohash* family is deprecated: https://github.com/vincenthz/hs-cryptohash#readme in favor of cryptonite family, SHA512 is there also.

Apparently `cryptonite` will have [trouble upgrading to GHC 9.2](https://github.com/haskell-infra/hackage-trustees/issues/305#issuecomment-861895222). It sounds like cryptohash-sha512 is easier to port. It now has a revision for GHC 9. So maybe there is also an argument for not migrating an existing `cryptohash-sha512` codebase to `cryptonite` given that Vincent is also not very active?

**Comment by Anton-Latukha** [comment]
That statement (citation that people keep citing) is wrong (as I forgot about that shenanigans story) (therefore I deleted it to stop mislead people). I would abstrain from comments, but we observe the current results.

At least they'd both needed to make sure that enough active/interested people have stack access...

As it can be said (stating the obvious)  ... khm `cryptohash-*` package family was not worked on from the fork/split, the whole set rolled down on the drive-by contributor fixes & version bumps, but eventually no one shows up to merge them.

GHC 9.0 was more then a half year ago. That meant `cryptohash-*` set shown its nature. Which meant a set of problems & effort of troubleshooting & workarounds `{HNix{,-Store-{Core,Remote},DHall{,-Nix{,pkgs}}`, I can not say how much project infra overloading/patching too for me (~2-4 days), which was essentially a wasted time & that is was only me with HNix packages...

As you see - the `cryptohash-*` family is abandonned (to put lightly & shortly), even the 8.10 PR merge is stalled. Therefore so is #8. It is also why https://github.com/Anton-Latukha/cryptohash-sha512/tree/ghc-8.10 was there (but I forgot is all those changes are right).

To not have that - I already ported projects to `cryptonite`.

As we see in the mentioned https://github.com/haskell-infra/hackage-trustees/issues/305#issuecomment-861895222
> `cryptonite` will be massively broken by sized primitives in GHC 9.2, see https://gitlab.haskell.org/ghc/head.hackage/-/blob/master/patches/basement-0.0.12.patch

It means that somebody (this time it was `RyanGlScott`) developed the patches, and the patches are out of the "project" tree. & that means that `cryptohash` in fact can `9.2`, but would recieve a API breackage (which I am Ok with).

The proper solution at this point is to take over this  hashing stuff.

**Pull request closed without merging**
